version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    container_name: test01
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pass
      - POSTGRES_USER_FILE=/run/secrets/user
      - POSTGRES_DB_FILE=/run/secrets/dbname
    secrets:
      - pass
      - user
      - dbname
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
secrets:
  pass:
    file: ./secrets/db_password
  user:
    file: ./secrets/db_user
  dbname:
    file: ./secrets/db_name
